<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
    <Using Include="NSubstitute" />
    <Using Include="NSubstitute.ExceptionExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Girder.Infrastructure/Girder.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Girder.InMemory/Girder.InMemory.csproj" />
    <ProjectReference Include="../../src/Girder.Redis/Girder.Redis.csproj" />
    <ProjectReference Include="../../src/Girder.Data.EntityFrameworkCore/Girder.Data.EntityFrameworkCore.csproj" />
    <ProjectReference Include="../../src/Girder.Messaging.MassTransit/Girder.Messaging.MassTransit.csproj" />
  </ItemGroup>

</Project>
